<!-- html -->
<template>
  <g-space>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
  </g-space>
</template>