<!-- html -->
<template>
  <g-space inline justifyContent="space-between" >
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
  </g-space>
</template>
