<!-- html -->
<template>
  <m-space inline justifyContent="space-between" >
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
  </m-space>
</template>
