<!-- html -->
<template>
  <g-space :size="[10, 10]">
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
  </g-space>
</template>